apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-qwen
  labels:
    managed-by: argocd-demo-v3-v2
    app: vllm-qwen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-qwen
  template:
    metadata:
      labels:
        app: vllm-qwen
    spec:
      containers:
      - name: vllm-qwen
        image: docker.io/library/vllm-qwen:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        resources:
          limits:
            nvidia.com/gpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-qwen-svc
spec:
  selector:
    app: vllm-qwen
  ports:
  - port: 8000
    targetPort: 8000
